//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled Shopping Central
//  @ File Name : SearchCustomerModel.cs
//  @ Date : 2/22/2013
//  @ Author :  khoatd
//
//


using System.Collections.Generic;
using System.ComponentModel;
using lhk.POS.Core.Domain;

namespace lhk.POS.Presentation.Models
{
    public class CustomerFinderModel : INotifyPropertyChanged
    {
        private Customer _customer;

        public delegate void SearchCustomerDelegate();
        public SearchCustomerDelegate SearchCustomerFn;

        public CustomerFinderModel(Customer customer)
        {
            _customer = customer;
        }

        public Customer Customer
        {
            get { return _customer; }
            set { _customer = value; }
        }


        private List<Customer> _customers;
        public List<Customer> Customers
        {
            get { return _customers; }
            set { _customers = value; InvokePropertyChanged(new PropertyChangedEventArgs("Customers")); }
        }


        public string Phone
        {
            get { return _customer.Phone; }
            set { _customer.Phone = value; InvokePropertyChanged(new PropertyChangedEventArgs("Phone")); SearchCustomerFn(); }
        }

        public string Name
        {
            get { return _customer.Name; }
            set { _customer.Name = value; InvokePropertyChanged(new PropertyChangedEventArgs("Name")); SearchCustomerFn(); }
        }

        #region Implementation of INotifyPropertyChanged

        public event PropertyChangedEventHandler PropertyChanged;

        public void InvokePropertyChanged(PropertyChangedEventArgs e)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, e);
        }

        #endregion
    }
}
