//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled Shopping Central
//  @ File Name : ProductGridDBController.cs
//  @ Date : 2/22/2013
//  @ Author :  khoatd
//
//


namespace SC_Core.component.productgridview
{
	public class ProductGridDBController {
	}
}
