//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled Shopping Central
//  @ File Name : SearchProductModel.cs
//  @ Date : 2/22/2013
//  @ Author :  khoatd
//
//


using System.Collections.Generic;
using System.ComponentModel;
using lhk.POS.Core.Domain;

namespace lhk.POS.Presentation.Models
{
    public class ProductFinderModel : INotifyPropertyChanged
    {
        private Product _product;

        public delegate void SearchProductDelegate();
        public SearchProductDelegate SearchProductFn;

        public ProductFinderModel(Product product)
        {
            _product = product;
        }

        public Product Product
        {
            get { return _product; }
            set { _product = value; }
        }


        private List<Product> _products;
        public List<Product> Products
        {
            get { return _products; }
            set { _products = value; InvokePropertyChanged(new PropertyChangedEventArgs("Products")); }
        }


        public string Barcode
        {
            get { return _product.Barcode; }
            set { _product.Barcode = value; InvokePropertyChanged(new PropertyChangedEventArgs("Barcode")); SearchProductFn(); }
        }

        public string Name
        {
            get { return _product.Name; }
            set { _product.Name = value; InvokePropertyChanged(new PropertyChangedEventArgs("Name")); SearchProductFn(); }
        }

        #region Implementation of INotifyPropertyChanged

        public event PropertyChangedEventHandler PropertyChanged;

        public void InvokePropertyChanged(PropertyChangedEventArgs e)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, e);
        }

        #endregion
    }
}
