//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled Shopping Central
//  @ File Name : SearchProdcutController.cs
//  @ Date : 2/22/2013
//  @ Author :  khoatd
//
//

using System.Collections.Generic;
using System.Linq;
using System;
using System.Windows.Forms;
using lhk.POS.Common.Business;
using lhk.POS.Presentation.Models;
using lhk.POS.Presentation.Views;
using Nop.Core.Infrastructure;
using lhk.POS.Core.Domain;
using lhk.POS.Core.Util;
using PosSystem.Depency;
using lhk.POS.Data;

namespace lhk.POS.Presentation.Presenters
{
    public class CustomerFinderPresenter
    {

        protected CustomerFinderModel _model;
        protected CustomerBusiness _business;
        private ICustomerFinderView _view;

        public CustomerFinderPresenter(ICustomerFinderView view)
        {
            _business = new CustomerBusiness(Singleton<PosEngine>.Instance.Resolve<IRepository<Customer>>());
            _view = view;

            _model = new CustomerFinderModel(new Customer());
            _model.Customers = new List<Customer>();
            _model.SearchCustomerFn = new CustomerFinderModel.SearchCustomerDelegate(HandleSearchCustomer);

            _view.InitView(_model);
        }

        public void HandleSearchCustomer()
        {
            try
            {
                AppLogger.logInfo(this.GetType().Name, " ENTER HandleSearchCustomer");

                var name = _model.Name ?? "";
                var customers = from p in _business.GetAll()
                                where p.Phone.Contains(_model.Phone ?? "") && p.Name.ToLower().Contains(name.ToLower() ?? "")
                               select p;

                _model.Customers = customers.ToList();
            }
            catch (Exception exc)
            {
                MessageBox.Show(exc.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                AppLogger.logError(this.GetType().Name, exc);

            }
        }

    }
}
