//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : @ ShoppingCentral
//  @ File Name : PaymentDetailController.cs
//  @ Date : 2/21/2013
//  @ Author :  kenjuzi
//
//
using System;
using System.Linq;
using System.Data;
//using CrystalDecisions.CrystalReports.Engine;
using System.Drawing.Printing;
using System.Threading;
using System.Collections.Generic;
using System.Text;
using lhk.POS.Presentation.Models;
using lhk.POS.Presentation.Views;
using lhk.POS.Common.Business;
using lhk.POS.Data;
using PosSystem.Depency;
using Nop.Core.Infrastructure;
using lhk.POS.Core.Domain;
using lhk.POS.Core.Util;

namespace lhk.POS.Presentation.Presenters
{
    public class PaymentDetailPresenter
    {

        protected PaymentDetailModel _model;
        protected OrderBusiness _businessOrder;
        protected OrderItemBusiness _businessOrderItem;
        protected CustomerBusiness _businessCustmer;
        protected IPaymentDetailView _view;

        public PaymentDetailPresenter(IPaymentDetailView view, Order order, Customer customer)
        {
            _businessOrder = new OrderBusiness(Singleton<PosEngine>.Instance.Resolve<IRepository<Order>>());
            _businessOrderItem = new OrderItemBusiness(Singleton<PosEngine>.Instance.Resolve<IRepository<OrderItem>>());
            _businessCustmer = new CustomerBusiness(Singleton<PosEngine>.Instance.Resolve<IRepository<Customer>>());
            _view = view;

            _model = new PaymentDetailModel(order, customer);

            _view.InitView(_model);
        }

    }
}
