//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : Contansts.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//

using System.ComponentModel;
namespace lhk.POS.Core
{
    public class Constants
    {
        #region DB Constants
        public static string FIELD_CONFIGURATION_GET_IP_ADDRESS = "GET_IP_ADDRESS";
        public static string FIELD_CONFIGURATION_DEPARTURE_HOUR = "DEPARTURE_HOUR";
        public static string FIELD_CONFIGURATION_DEPARTURE_MINUTE = "DEPARTURE_MINUTE";
        public static string FIELD_CONFIGURATION_MAINTAINER_EMAIL_ADDRESS_FROM = "MAINTAINER_EMAIL_ADDRESS_FROM";
        public static string FIELD_CONFIGURATION_MAINTAINER_EMAIL_ADDRESS_PASS = "MAINTAINER_EMAIL_ADDRESS_PASS";
        public static string FIELD_CONFIGURATION_MAINTAINER_EMAIL_ADDRESS_TO = "MAINTAINER_EMAIL_ADDRESS_TO";
        public static string FIELD_CONFIGURATION_SEND_MAINTENANCE_MAIL_HOUR = "SEND_MAINTENANCE_MAIL_HOUR";

        public static int DEFAULT_VALUE_DEPARTURE_HOUR = 16;
        public static int DEFAULT_VALUE_DEPARTURE_MINUTE = 0;

        public static string INSERT_ACTION = "INSERT";
        public static string UPDATE_ACTION = "UPDATE";
        public static string INSERT_UPDATE_ACTION = "INSERT OR UPDATE";
        public static string DELETE_ACTION = "DELETE";

        //------------------------------------------------------------//
        // USER
        //------------------------------------------------------------//
        public enum UserRole
        {
            [Description("Quản trị viên")]
            Admin,
            [Description("Quản lý")]
            Supervisor,
            [Description("Nhân viên")]
            Staff
        }

        //------------------------------------------------------------//
        // FINANCIAL
        //------------------------------------------------------------//
        public enum RevenueType
        {
            [Description("Bán vé")]
            Ticket,
            [Description("Hóa đơn lẻ")]
            IrregularOrder,
            [Description("Hóa đơn sĩ")]
            RegularOrder,
            [Description("Điều chỉnh")]
            Adjustment,
            [Description("Khác")]
            Other
        }
        #endregion

        public const decimal MAX_MONEY_VALUE = (decimal)1e+12 - 1; // 999,999,999,999
        public const double MAX_WEIGHT_VALUE = 1.79e+308;


        public static class Messages
        {
            #region COMMON

            public const string CONFIRMATION_CAPTION = "Xác nhận";
            public const string CONFIRMATION_ACTION_CONFIRM = "Chấp nhận?";
            public const string ERROR_CAPTION = "Lỗi";
            public const string ERROR_OPERATION_NOT_PERFORMED = "Có lỗi xảy ra. Không thể thực hiện yêu cầu.";
            public const string INFO_CAPTION = "Thông báo";
            public const string WARNING_CAPTION = "Cảnh báo";

            #endregion

            #region LOGIN FORM

            public const string BLANK_USERNAME_ALERT = "Tên người dùng không được trống.";
            public const string BLANK_PASSWORD_ALERT = "Mật khẩu không được trống.";
            public const string INVALID_USERNAME_OR_PASSWORD = "* Tên Người Dùng hoặc Mật Khẩu không chính xác.";
            public const string INVALID_USER_ROLE = "Hệ thống không được thiết lập đúng với quyền người dùng.";

            #endregion

            #region ITEMS LIST

            public const string ITEM_DELETE_CONFIRMATION_CAPTION = "Xác nhận";
            public const string ITEM_DELETE_CONFIRMATION_MESSAGE = "Bạn có chắc chắn muốn xóa món hàng này?";

            #endregion

            #region PRODUCT

            public const string PRODUCT_NAME_NOT_EMPTY = "Tên sản phẩm không được để trống!";
            public const string PRODUCT_BARCODE_NOT_EMPTY = "Mã vạch sản phẩm không được để trống!";
            public const string PRODUCT_CATEGORY_NOT_EMPTY = "Phân loại sản phẩm không được để trống!(Chọn phần loại sản phẩm phía bên trái)";
            public const string PRODUCT_PRICE_GREATER_THAN_ZERO = "Giá bán phải lớn hơn 0";
            public const string PRODUCT_COST_GREATER_THAN_ZERO = "Giá Nhập phải lớn hơn 0";

            public const string PRODUCT_SELECT_PRODUCT = "Hảy chọn sản phẩm!";
            public const string PRODUCT_SELECT_IMPORT = "Hảy chọn mã nhập hàng!";

            public const string PRODUCT_DULICATE_BARCODE = "Mã vạch này đã được sử dụng!";

            #endregion

            #region TICKET
            public const string MSG_TICKET_INSUFFICIENT_PERMISSION = "Không có quyền xử lý vé này!";
            public const string MSG_TICKET_BEFORE_DATETIME_ERROR_MSG = "Ngày bán vé không hợp lệ. Hãy chọn ngày nhỏ hơn!";
            public const string MSG_TICKET_DATETIME_SMALLER_CURRENTDATE = "Ngày đặt vé không nhỏ hơn ngày hiện tại";
            public const string MSG_TICKET_NAME_ERROR_MSG = "Họ Tên không được rỗng.";
            public const string MSG_TICKET_ID_PHONE_ERROR_MSG = "Phải nhập chứng minh nhân dân hoặc số điện thoại.";
            public const string MSG_TICKET_PHONE_NUMBER_RANGE_ERROR_MSG = "Số điện thoại không hơn 11 số";
            public const string MSG_TICKET_SELECT_SEAT_REQUIRE = "Chọn 1 hoặc nhiều ghế trước khi tạo vé";
            public const string MSG_TICKET_TICKET_EXIST_ERROR_MSG = "Vé đã tồn tại. Vui lòng nhấn cập nhật để thay đổi thông tin.";
            public const string MSG_TICKET_INFO_TICKET_PRICE_CONFIG_NOT_FOUND_FOR_SEAT_CLASS = "Không có thiết lập giá vé cho hạng ghế này.";
            public const string MSG_TICKET_SEAT_NOT_AVAILABLE = "Ghế đã được mua hoặc chuyến xe này đã hoàn thành. Vui lòng chọn ghế khác.";

            public const string MSG_TICKET_TICKET_NOT_EXIST_MSG = "Vé chưa tồn tại. Vui lòng thêm mới vé này.";
            public const string MSG_TICKET_DELETE_TICKET_NOT_EXIST_MSG = "Vé chưa tồn tại nên không thể hủy.";
            public const string MSG_TICKET_DELETE_TICKET_CONFIRM_MSG = "Bạn có chắc muốn hủy vé này?";
            public const string MSG_TICKET_INSERT_TICKET_EXCEPTION_MSG = "Error occurs when Create New Ticket.";
            public const string MSG_TICKET_UPDATE_TICKET_EXCEPTION_MSG = "Error occurs when Update Ticket.";
            public const string MSG_TICKET_DELETE_TICKET_EXCEPTION_MSG = "Error occurs when Delete Ticket.";
            public const string MSG_TICKET_PRINT_TICKET_EXCEPTION_MSG = "Error occurs when Print Ticket.";

            public const string MSG_TICKET_INSERT_TICKET_FAIL_MSG = "Thêm vé không thành công.";
            public const string MSG_TICKET_INSERT_TICKET_SUCCESS_MSG = "Thêm vé thành công.";
            public const string MSG_TICKET_UPDATE_TICKET_FAIL_MSG = "Cập nhật vé không thành công.";
            public const string MSG_TICKET_UPDATE_TICKET_SUCCESS_MSG = "Cập nhật vé thành công.";
            public const string MSG_TICKET_DELETE_TICKET_SUCCESS_MSG = "Hủy vé thành công.";
            public const string MSG_TICKET_DELETE_TICKET_FAIL_MSG = "Hủy vé không thành công.";
            public const string MSG_TICKET_PRINT_TICKET_FAIL_MSG = "In vé không thành công.";
            public const string MSG_TICKET_RETURN_TICKET_FEE_MSG = "(Sẽ mất {0}VND phí hủy vé.)";
            #endregion
        }
    }
}
