//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : CurrencyUtil.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//


namespace lhk.POS.Core.Util
{
    public static class CurrencyUtil
    {
        public static string ToString(decimal value)
        {
            return value.ToString("N0");
        }

        public static string ToStringWithCurrencySign(decimal value)
        {
            return value.ToString("C0", System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN"));
        }

        public static decimal ToDecimal(string s)
        {
            decimal value = 0;
            if (decimal.TryParse(s, out value))
            {
                return value;
            }
            if (decimal.TryParse(s,
                System.Globalization.NumberStyles.AllowCurrencySymbol, 
                System.Globalization.CultureInfo.CreateSpecificCulture("vi-VN"),
                out value))
            {
                return value;
            }

            return -1;
        }
    }
}
