//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : FileReader.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//


namespace lhk.POS.Core.Util{
	public class FileReader {
	}
}
